name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.4"

    env:
      BUNDLE_PATH_RELATIVE_TO_CWD: true

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          bundler: default
          rubygems: latest
      - name: Run Standard
        run: bundle exec standardrb
      - name: Run the default task
        run: bundle exec rake